#!/run/current-system/sw/bin/zsh

function make_link() {
	file="$1"
	link="$2"
	mkdir -p "$(dirname "$link")"
	ln -s "$file" "$link"
}
function process_link() {
	file="$1"
	link="$2"
	if [ -L "$link" ]; then
		old=$(readlink "$link")
		if [ "$old" != "$file" ]; then
			echo "\
Re-directing symlink:
       "$link"
old -> "$old"
new -> "$file""
			rm "$link"
			make_link "$file" "$link"
		fi
	else
		echo "\
Making symlink:
   "$link"
-> "$file""
		make_link "$file" "$link"
	fi
}

root="$(git rev-parse --show-toplevel)/home/"
while IFS= read -r file; do
	relative="$(realpath --relative-to="$root" "$file")"
	process_link "$file" "$HOME/$relative"
done <<<"$(fd -H -t=f . $root)"
